name: Fix

on:
  schedule:
    - cron: "17,47 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - name: Run fixer
        run: npm run fix-titles
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_UNTITLED_VIEW_ID: ${{ secrets.NOTION_UNTITLED_VIEW_ID }}
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "chore: keepalive [skip ci]"
